apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
  - namespace.yaml
  - config.yaml
  - rustfs.yaml
  - postgres.yaml
  - migrate.yaml
  - app.yaml
  - frontend.yaml
  - ingress.yaml

secretGenerator:
  - name: secrets
    type: Opaque
    envs:
      - .env.k8s